### ISSUE TITLE
Custom domain reference for CRX Maven Plugin failing

### ISSUE THREAD

**Issue by GregDomjan** [bmatthews68/crx-maven-plugin#10]
The readme.md has link CRX Maven Plugin http://crx-maven-plugin.btmatthews.com/
Displays error page.

>  Oh no! It looks like this Pages site has been disabled due to a misconfigured custom domain.

Can still get to doc at 
http://bmatthews68.github.io/crx-maven-plugin/

**Comment by bmatthews68** [comment]
Updated DNS
